version: 2

general:
  branches:
    ignore:
      - gh-pages

jobs:
  "analyse-gcc":
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Set up system
          command: /root/project/.circleci/setup.sh && apt install --yes --quiet clang-tidy
      - restore_cache:
          key: cache
      - run:
          name: Run analyser
          command: bash -c /root/project/linux/analyse.sh
      - save_cache:
          key: cache
          paths:
            - ~/.ccache
            - ~/.conan/data

  "sanitize-gcc":
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Set up system
          command: /root/project/.circleci/setup.sh
      - restore_cache:
          key: cache
      - run:
            name: Run sanitizer
            command: bash -c /root/project/linux/sanitize.sh
      - save_cache:
          key: cache
          paths:
            - ~/.ccache
            - ~/.conan/data

  "analyse-clang":
    docker:
      - image: clangbuiltlinux/ubuntu
    steps:
      - checkout
      - run:
          name: Set up system
          command: /root/project/.circleci/setup.sh && apt install --yes --quiet clang-tidy
      - restore_cache:
          key: cache
      - run:
          name: Run analyser
          command: CXX=/usr/bin/clang++-9 CC=/usr/bin/clang-9 /root/project/linux/analyse.sh
      - save_cache:
          key: cache
          paths:
            - ~/.ccache
            - ~/.conan/data

  "sanitize-clang":
    docker:
      - image: clangbuiltlinux/ubuntu
    steps:
      - checkout
      - run:
          name: Set up system
          command: /root/project/.circleci/setup.sh
      - restore_cache:
          key: cache
      - run:
          name: Run sanitizer
          command: CXX=/usr/bin/clang++-9 CC=/usr/bin/clang-9 /root/project/linux/sanitize.sh
      - save_cache:
          key: cache
          paths:
            - ~/.ccache
            - ~/.conan/data

workflows:
  version: 2
  test:
    jobs:
      - "analyse-gcc"
      - "sanitize-gcc"
      - "analyse-clang"
      - "sanitize-clang"
