version: 2

general:
  branches:
    ignore:
      - gh-pages

jobs:
  "analyse":
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Set up system
          command: /root/project/.circleci/setup.sh
      - restore_cache:
          key: cache
      - run:
          name: Run analyser
          command: bash -c /root/project/linux/analyse.sh
      - save_cache:
          key: cache
          paths:
            - ~/.ccache
            - ~/.conan/data

  "sanitize":
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Set up system
          command: /root/project/.circleci/setup.sh
      - restore_cache:
          key: cache
      - run:
            name: Run sanitizer
            command: bash -c /root/project/linux/sanitize.sh
      - save_cache:
          key: cache
          paths:
            - ~/.ccache
            - ~/.conan/data

workflows:
  version: 2
  test:
    jobs:
      - "analyse"
      - "sanitize"
