#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../../..; pwd)

conan install \
  --build=missing \
  --env "CONAN_CMAKE_TOOLCHAIN_FILE=$PROJECT_DIR/.github/workflows/toolchains/linux-cppcheck.cmake" \
  "${PROJECT_DIR}" \
  "$@"

conan build \
  "${PROJECT_DIR}"
