#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../../..; pwd)

conan install \
  --build=missing \
  --env wss:CXXFLAGS="-pedantic -Wall -Werror -Wextra" \
  --settings build_type=Debug \
  "${PROJECT_DIR}" \
  "$@"

conan build \
  "${PROJECT_DIR}"
