#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../../..; pwd)

conan install \
  --build=missing \
  --env wss:CXXFLAGS="-D_GLIBCXX_ASSERTIONS -fsanitize=address,undefined \
-pedantic -Wall -Werror -Wextra -Wno-maybe-uninitialized" \
  "${PROJECT_DIR}" \
  "$@"

conan build \
  "${PROJECT_DIR}"
