#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../../..; pwd)

conan install \
  --build=missing \
  --env CONAN_CMAKE_TOOLCHAIN_FILE="${PROJECT_DIR}/.github/workflows/toolchains/linux-gcc.cmake" \
  --profile default \
  --profile "${PROJECT_DIR}/.github/workflows/conan/linux-profile" \
  "${PROJECT_DIR}" \
  "$@"

conan build \
  "${PROJECT_DIR}"
