#!/usr/bin/env bash

set -euo pipefail

PROFILE=$1
PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)

shift

conan build \
  --output-folder=. \
  --profile:build=./detected \
  --profile:build="$PROJECT_DIR"/workflows/conan/profiles/"$PROFILE" \
  --profile:host=./detected \
  --profile:host="$PROJECT_DIR"/workflows/conan/profiles/"$PROFILE" \
  "$@" \
  "${PROJECT_DIR}"
