#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)

"$PROJECT_DIR"/workflows/conan/install clang-tidy-fix

"$PROJECT_DIR"/workflows/conan/build clang-tidy-fix \
  --configure

cmake \
  --build . \
  --parallel 1
