#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)
NUM_CPUS=$(nproc)
export CC=clang
export CXX=clang++

"$PROJECT_DIR"/workflows/conan/install clang-static-analyzer

scan-build \
  -o /tmp/scan-build \
  --status-bugs \
  --use-c++=c++ \
  --use-cc=cc \
    cmake \
      "${PROJECT_DIR}" \
      -DCMAKE_MODULE_PATH="$(pwd)" \
      -DCMAKE_CXX_FLAGS="-DNDEBUG"

scan-build \
  -o scan-build \
  --status-bugs \
  --use-c++=c++ \
  --use-cc=cc \
    cmake \
      --build . \
      --clean-first \
      -- \
      --jobs "${NUM_CPUS}"
