#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)

"$PROJECT_DIR"/workflows/conan/install clang-tidy-fix

conan build \
  --configure \
  "${PROJECT_DIR}"

cmake \
  --build . \
  --parallel 1
