#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)

"$PROJECT_DIR"/workflows/conan/install iwyu

conan build \
  "${PROJECT_DIR}" | tee iwyu-output.txt

# CMake doesn't treat iwyu-related warnings as errors.
# Instead grep for warning from iwyu and exit with an error
if grep "Warning: include-what-you-use reported diagnostics:" iwyu-output.txt > /dev/null
then
  echo error: include-what-you-use issued warnings
  cmake --build . --target clean
  exit 1
fi
