#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)

conan install \
  --build=missing \
  --env wss:CONAN_CMAKE_TOOLCHAIN_FILE="$PROJECT_DIR"/workflows/conan/toolchains/linux-libfuzzer.cmake \
  --env wss:CXXFLAGS="-Wall -Werror -Wextra -Wshadow -fsanitize=address,undefined -g -pedantic" \
  --settings build_type=Release \
  --settings compiler.libcxx=libstdc++11 \
  "${PROJECT_DIR}" \
  "$@"

conan build \
  --configure \
  "${PROJECT_DIR}"

cmake \
  --build . \
  --parallel "$(nproc)"

ctest \
  --output-on-failure \
  -R fuzz
