#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)
export CC=clang
export CXX=clang++

"$PROJECT_DIR"/workflows/conan/install libfuzzer

"$PROJECT_DIR"/workflows/conan/build libfuzzer \
  --configure

cmake \
  --build . \
  --parallel "$(nproc)"

ctest \
  --output-on-failure \
  -R fuzz
