#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)
export CXX=clang++

"$PROJECT_DIR"/workflows/conan/install libfuzzer

conan build \
  --configure \
  "${PROJECT_DIR}"

cmake \
  --build . \
  --parallel "$(nproc)"

ctest \
  --output-on-failure \
  -R fuzz
