#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)

conan install \
  --build=missing \
  --env wss:CXXFLAGS="-pedantic -Wall -Werror -Wextra -Wshadow" \
  --settings build_type=Release \
  --settings compiler.libcxx=libstdc++11 \
  "${PROJECT_DIR}" \
  "$@"

conan build \
  "${PROJECT_DIR}"
