#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)
export CC=clang
export CXX=clang++

"$PROJECT_DIR"/workflows/conan/install test-clang
"$PROJECT_DIR"/workflows/conan/build test-clang
