#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)
export CC=gcc
export CXX=g++

"$PROJECT_DIR"/workflows/conan/install test-gcc

"$PROJECT_DIR"/workflows/conan/build test-gcc
