#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../..; pwd)

"$PROJECT_DIR"/workflows/conan/install valgrind

conan build \
  --configure --build \
  "${PROJECT_DIR}"

ctest \
  --output-on-failure \
  --overwrite MemoryCheckCommandOptions="-q --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=50 --error-exitcode=1" \
  --parallel "$(nproc)" \
  --test-action memcheck
