#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")"/../../..; pwd)
NUM_CPUS=$(nproc)

cmake \
  -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake \
  -DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS -fsanitize=address,undefined \
-pedantic -Wall -Werror -Wextra -Wno-maybe-uninitialized -Wno-restrict" \
  -G Ninja \
  "${PROJECT_DIR}"

cmake \
  --build . \
  --parallel "${NUM_CPUS}"

ctest \
  --output-on-error \
  --parallel "${NUM_CPUS}"
